[package]
name = "RustBot"
version = "0.1.0"
edition = "2018"

[dependencies]
serenity = "0.12.2"
tokio = { version = "1.40.0", features = ["full"] }
dotenv = "0.15.0"
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio-native-tls"] }